name: Android APK (Flutter)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run if this repo has a Flutter/Android project
    if: ${{ hashFiles('**/pubspec.yaml') != '' || hashFiles('**/android/gradlew') != '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          # (Removed: cache: gradle) → avoids scanning for gradle files in non-Android repos

      - name: Install Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            cmdline-tools;latest

      - name: Accept SDK licenses
        shell: bash
        run: |
          SDKROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
          yes | "${SDKROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Enable Android (no-op if already enabled)
        run: flutter config --enable-android

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

